spring:
  ### datasource
  datasource:
    url: # url
    username: # username
    password: # password
    driver-class-name: # driver-class-name

  ### jpa
  jpa:
    database: # database
    open-in-view: off
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  properties:
    secret-key: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 # secret-key
    expiration-time: 3600 # expiration-time
